import z from "zod";

export const formSchema = z.object({
  companyName: z.string(),
  physicalAddress: z.string(),
  title: z.string(),
  website: z.string(),
  firstName: z.string(),
  state: z.string(),
  zipCode: z.string(),
  country: z.string(),
  lastName: z.string(),
  contactEmail: z.string(),
  contactPhone: z.string(),
  contactAddress: z.string(),
  businessType: z.string(),
  agentsNumber: z.string(),
  portsNumber: z.string(),
  ipAddress: z.string(),
  campaign: z.string(),
  additionalInfo: z.string().optional(),
  file: z.instanceof(File).optional(),
  frontSide: z.instanceof(File).optional(),
  backSide: z.instanceof(File).optional(),
  nationalId: z.string(),
  bussinessCountry: z.string(),
  frontSideUrl: z.string().optional(),
  backSideUrl: z.string().optional(),
  fileUrl: z.string().optional(),
});
